### ISSUE TITLE
Custom variable Storage requires "display" method

### ISSUE THREAD

**Issue by mnbroatch** [alforno/bondage.js#1]
A comment in `runner.js` says about variable storage: "This must simply contain a 'get(name)' and 'set(name, value)' function". However, evaluating a variable in an inline expression requires a "display()" method. This is a little inconvenient for those wanting to simply supply a `new Map([some entries])`.

**Comment by alforno** [comment]
The new DefaultVariableStorage contains a default implementation for the display method. This additional requirement was needed because there has to be a way to format a variable for display in some cases. An example of this is display currency like this "$5.50" instead of "$5.496583712383". There are other issues related to displaying variables too. 
I'm going to close this, because I have no other feasable way to implement this. 
My recommendation is that if you don't want to make custom code for the display method, then use the default implementation of DefaultVariableStorage. The alternative is to copy/paste the default display method implementation into your custom storage code.

**Comment by mnbroatch** [comment]
I think the best solution might just be to use a function

**Comment by alforno** [comment]
If I can implement functions within inline expressions, then I agree that a function would be more aligned to YarnSpinner specs.

**Comment by alforno** [comment]
It's possible that I'm over complicating this, since function calls can return text outside of an expression. There might be a use case where the results of a command/function call needs to be part of a calculation within an inline expression. I'll have to experiment with it to figure out my approach.

**Comment by alforno** [comment]
Now that I have a simple implementation of functions inside of an inline expression, I'll be removing the display function from storage. Thanks for the suggestion.

**Comment by alforno** [comment]
Display has been removed with commit 43455dd.
