### ISSUE TITLE
Function calls do not work inside an inline expression.

### ISSUE THREAD

**Issue by mnbroatch** [alforno/bondage.js#4]
`<<set $someVar to someFunction()>>`

works, but

`The value is {someFunction()}`

does not.

**Comment by alforno** [comment]
My progress is slow on these things, but I will look int this and your other reported issues to see what the effort is to support theses features. There are some issues that I know about and that I've decided not to address, either because there are feasable work-arounds or because I don't need that functionality. I know, it may seem selfish, but I have a limited time budget for this project. Regards.

**Comment by alforno** [comment]
When I added inline expression, I think there was a challenge in getting the function call to work. I might revisit it later, but there is a workaround and that is to assign the results of the function to a variable then display it. I'll leave the issue open for now.

**Comment by mnbroatch** [comment]
No worries, I've started looking into these things myself, so I would say don't even worry about it until I hit brick walls of my own :P

**Comment by alforno** [comment]
I was able to implement partial support for function/command calls within an inline expression. It does not support combining expressions and function calls within an inline expression, due to some challenges with lexing and parsing. I might revisit this later, but closing for now since the example shown is now supported.
